FROM python:3.9.16-slim-bullseye
WORKDIR /backend

#env değişkeni tanımlama
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

COPY . .
RUN pip install -r requirements.txt
#?buraya kadar build aşaması
EXPOSE 8000

CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]